apiVersion: v1
kind: Pod
metadata:
  name: cohab-gpu-pod
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 2
        cpu: "2"
        memory: "12Gi"
    volumeMounts:
    - name: ekphrasis2-persistent-storage
      mountPath: /home/jovyan/work
    - name: dshm
      mountPath: /dev/shm

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-RTX-A6000
  volumes:
    - name: ekphrasis2-persistent-storage
      persistentVolumeClaim:
        claimName: ekphrasis2-pv-claim
    - name: dshm
      emptyDir:
        medium: Memory